name: AxolotMine
main: dev.silentbit.axolotMine.AxolotMine
version: 1.0.0
api-version: '1.21'
folia-supported: true
author: SilentBit
description: A Folia-safe mine reset plugin inspired by RealMines (Admin Only)

depend: [WorldEdit]
softdepend: [PlaceholderAPI, Worlds]

commands:
  axolotmine:
    description: Manage all Axolot mines (Admin Only)
    usage: /axolotmine [create|reset|delete|list|reload] [args]
    aliases: [am, mine, mines]
    permission: axolotmine.admin

permissions:
  axolotmine.admin:
    description: Full access to manage mines (Admin Only)
    default: op
